### ISSUE TITLE
question for Tyler

### ISSUE THREAD

**Issue by albaez7** [ctagroup/home-app#38]
A student asked...
Can I have dump of the HomeApp DB or SQL scripts to install DB with test data? I guess this DB will have users and group information.
Reason for asking for dump of "HomeApp DB" is that by looking at the diagram here  and web.config, it seems like the user and group info that I need for chat, will be available in it. 
As per https://github.com/ctagroup/home-app/blob/master/SurveyAdmin/SurveyAdmin/Web.config, I am looking for this exactly -  Initial Catalog=SurveyAndSite which is name of the database.
If I get these artifacts by tomorrow, I can study this over the weekend and we can meet early next week with my questions and possible solutions. 

So Eric is requesting me to post the db dump with test data to the github code repo, so others can access it as well

**Comment by tbahn** [comment]
I can definitely get you a copy of the database schema (the underlying structure), but I'd rather not try to generate test data, I don't know what the test data should look like.

Maybe you can do a few test/sample run with the app to generate the test data, and then I can just pull those rows and include them with the schema?

**Comment by Soomal** [comment]
Database structure or DDL SQL scripts should be helpful.

**Comment by tbahn** [comment]
I've added an sql script of the database schema to the repository, under the SurveyAdmin project folder. The script is formatted for MSSQL Server 2008.

File name is: SurveyandSite_2008_schema-only.sql

**Comment by Soomal** [comment]
Thanks for the script Tyler. I am closing this issue.

**Comment by tbahn** [comment]
Thanks.
