### ISSUE TITLE
Login to Hmis not working correctly on mobile

### ISSUE THREAD

**Issue by CTAJavier** [ctagroup/home-app#55]
When logging in to home app via mobile, after credentials are entered and submitted application hangs and does not return to app or actually log in. Tried on Chrome on android Marshmallow.

**Comment by desaiuditd** [comment]
Debugged this issue. It's not even working on iOS 9.3.1 Safari.

Attaching the screenshots.

<img width="1002" alt="screen shot 2016-05-05 at 14 37 45" src="https://cloud.githubusercontent.com/assets/2236554/15059477/d5c7ab3a-12d7-11e6-8bc5-345a9dbe80c6.png">

<img width="1000" alt="screen shot 2016-05-05 at 14 38 07" src="https://cloud.githubusercontent.com/assets/2236554/15059478/d5d5ce0e-12d7-11e6-93ce-97ea97f35b2d.png">

**Comment by desaiuditd** [comment]
this one is fixed.
